### PR TITLE
fixes #73 patterns that return ErrNotExist + WithFailOnIOErrors

### LINKED ISSUE #73: `Glob` incorrectly returns errors if pattern does not match when failing on IO errors
This code:

```go
matches, err := doublestar.Glob(fsys, "non-existent-path", doublestar.WithFailOnIOErrors())
```

incorrectly returns an error if `non-existent-path` does not exist. It should return an empty list of matches and no error.

The [`exists` function](https://github.com/bmatcuk/doublestar/blob/master/glob.go#L338-L342) is certainly buggy, as it returns an error when a file does not exist, whereas it should return `false` and no error. It should be something like:

```go
// Returns true if the path exists
func (g *glob) exists(fsys fs.FS, name string) (bool, error) {
	_, err := fs.Stat(fsys, name)
	if errors.Is(err, fs.ErrNotExist) { // name not existing is not an error
		return false, nil
	}
	return err == nil, g.forwardErrIfFailOnIOErrors(err)
}
```

### PR DESCRIPTION
**Pull request by bmatcuk**
Unfortunately, io.fs has poor support for symlinks, so, broken symlinks are _not_ treated as an IO error because there's no way to differentiate them from other non-existent paths specified as part of the pattern passed to doublestar. [There is a proposal](https://github.com/golang/go/issues/49580) to add better support to io.fs, at which point, we can revisit this behavior in doublestar.

### CODE REVIEW

File: glob.go [hunk 1]
```diff
@@ -336,15 +337,28 @@ func indexMatchedOpeningAlt(s string) int {
 }
 
 // Returns true if the path exists
-func (g *glob) exists(fsys fs.FS, name string) (bool, error) {
-	_, err := fs.Stat(fsys, name)
-	return err == nil, g.forwardErrIfFailOnIOErrors(err)
+func (g *glob) exists(fsys fs.FS, name string) (fs.FileInfo, bool, error) {
+	// name might end in a slash, but Stat doesn't like that
+	namelen := len(name)
+	if name[namelen - 1] == '/' {
```
Comment (twpayne) [inline glob.go:343]: This needs to be

```go
if namelen > 1 && name[namelen-1] == '/' {
```

to handle the case where name is `/`, otherwise `fs.Stat` gets called with name being an empty string, which returns a permission error.

**Review by twpayne — APPROVED** [review]
One minor bug discovered during testing, but overall LGTM.

Thank you very much for this :)

File: glob.go (hunk 1 above)
Comment (bmatcuk) [reply glob.go:343]: Good catch! Thanks!
